export enum ErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_EMAIL_EXISTS = "USER_EMAIL_EXISTS",
  POST_NOT_FOUND = "POST_NOT_FOUND",
  UPLOAD_NOT_FOUND = "UPLOAD_NOT_FOUND",
  CONFLICT = "CONFLICT",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
